# Generated by Django 4.0.1 on 2022-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='joined',
            field=models.BooleanField(null=True),
        ),
    ]
