# Generated by Django 4.0.1 on 2022-01-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='joined',
        ),
    ]
